import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import LoginSignupForm from './login'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Studious</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/studious-website-favicon-black.png" />
      </Head>
      <main className={styles.main}>
        <Image
          src="/studioustransparent.png"
          width={300}
          height={150}
        />
        <LoginSignupForm/>
      </main>
    </>
  )
}
